### ISSUE TITLE
[Feature] - Add version numbering to library

### ISSUE THREAD

**Issue by mercymantis** [Porthorian/vultr-php#7]
I'm using this library to automate my vultr projects but there's no version number association so I'm unable to isolate a specific revision with composer.   Also, because I did some bug-fixes/touch-ups, I wanted to create a patch file for the current revision.  When do you think we can see a version 0.0.1 or 1.0.0?

**Comment by Porthorian** [comment]
I've been tempted to start versioning some of the releases. But the reasoning why I haven't done it yet, is cause the library hasn't fully been tested yet or is complete. This library should have a full 1.0 release sometime in mid July.

Before than I guess I could release a 0.0.1 version for now

**Comment by Porthorian** [comment]
I pushed a version 0.1 for now till its finished and ill add minor version numbers as I finish up the rest of the features.

Thanks for taking interest in the project!

**Comment by mercymantis** [comment]
Thank you so much for going through all my requests, it helps out a lot.I haven't had time to pull the updated version, I'll do that tonight.Eric                                                                                                                                                                                                                                                                                                                                                     From: Vinnie MaroneSent: Wednesday, June 29, 2022 4:57 AMTo: vultr/vultr-phpReply To: vultr/vultr-phpCc: mercymantis; AuthorSubject: Re: [vultr/vultr-php] [Feature] - Add version numbering to library (Issue #7)
I've been tempted to start versioning some of the releases. But the reasoning why I haven't done it yet, is cause the library hasn't fully been tested yet or is complete. This library should have a full 1.0 release sometime in mid July.
Before than I guess I could release a 0.0.1 version for now

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/vultr/vultr-php/issues/7#issuecomment-1169713739",
"url": "https://github.com/vultr/vultr-php/issues/7#issuecomment-1169713739",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
